### ISSUE TITLE
Docs link not rendering in the UI next to form when creating a block

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect-openai#16]
The markdown link `[[OpenAPI Image generation docs]( https://beta.openai.com/docs/gu` isn't rendering when I go to create a block. See screenshot below.

This isn't a huge deal, but something we'll want to fit. I couldn't find the text in this repo, so couldn't fix myself.

<img width="896" alt="Screenshot 2023-01-28 at 8 47 38 AM" src="https://user-images.githubusercontent.com/7703961/215270143-f1c42704-2161-4bb5-94b5-f469a839d345.png">

**Comment by ahuang11** [comment]
I think this is an issue on the UI not rendering markdown. I don't think it can be fixed in this collection.

**Comment by ahuang11** [comment]
https://github.com/PrefectHQ/prefect/issues/8385
